WAVECARDS = [
	{"Izquierda": "Frio", "Derecha": "Caliente"},
	{"Izquierda": "Bajo", "Derecha": "Alto"},
	{"Izquierda": "Normal que se tenga", "Derecha": "Raro que se tenga"},
	{"Izquierda": "Vicio", "Derecha": "Virtud"},
	{"Izquierda": "Tema aburrido", "Derecha": "Tema fascinante"},
	{"Izquierda": "De poca cultura", "Derecha": "De mucha cultura"},
	{"Izquierda": "Habilidad subestimada", "Derecha": "Habilidad sobrevalorada"},
	{"Izquierda": "Inflexible", "Derecha": "Flexible"},
	{"Izquierda": "Sabio", "Derecha": "Inteligente"},
	{"Izquierda": "Mal sabor en la boca", "Derecha": "Buen sabor en la boca"},
	{"Izquierda": "Sitio ruidoso", "Derecha": "Sitio silencioso"},
	{"Izquierda": "Mal juego de mesa", "Derecha": "Buen juego de mesa"},
	{"Izquierda": "Pelicula Pochoclera", "Derecha": "Cine Arte"},
	{"Izquierda": "Realidad", "Derecha": "Ciencia Ficcion"},
	{"Izquierda": "Bueno", "Derecha": "Malo"},
	{"Izquierda": "Ancho", "Derecha": "Estrecho"},
	{"Izquierda": "Lindo", "Derecha": "Feo"},
	{"Izquierda": "Rapido", "Derecha": "Lento"},
	{"Izquierda": "Correcto", "Derecha": "Incorrecto"},
	{"Izquierda": "Compania mas malvada", "Derecha": "Compania menos malvada"},
	{"Izquierda": "Emoji no sexy", "Derecha": "Emoji Sexy"},
	{"Izquierda": "Juego subvalorado", "Derecha": "Juego sobrevalorado"},
	{"Izquierda": "Creible", "Derecha": "Increible"},
	{"Izquierda": "Comestible", "Derecha": "No comestible"},
	{"Izquierda": "Maduro", "Derecha": "Inmaduro"},
	{"Izquierda": "Historicamente importante", "Derecha": "Historicamente irrelevante"},
	{"Izquierda": "Arte", "Derecha": "Comercio"},
	{"Izquierda": "Geek", "Derecha": "Idiota"},
	{"Izquierda": "Se ve como una persona", "Derecha": "No se ve como una persona"},
	{"Izquierda": "Placer culpable", "Derecha": "Orgullosamente amado"},
	{"Izquierda": "Se siente bien", "Derecha": "Se siente mal"},
	{"Izquierda": "Parte dura de la vida", "Derecha": "Parte gratificante de la vida"},
	{"Izquierda": "Ameritrash", "Derecha": "Eurogame"},
	{"Izquierda": "Inocente", "Derecha": "Sexual"},
	{"Izquierda": "Superficial", "Derecha": "Profundo"},
	{"Izquierda": "Trabajo", "Derecha": "Placer"},
	{"Izquierda": "Carnivoro", "Derecha": "Vegano"},
	{"Izquierda": "Comodo", "Derecha": "Incomodo"},
	{"Izquierda": "Cercano", "Derecha": "Lejano"},
	{"Izquierda": "Digital", "Derecha": "Analógico"},
	{"Izquierda": "Fácil", "Derecha": "Difícil"},
	{"Izquierda": "Caro", "Derecha": "Barato"},
	{"Izquierda": "Rural", "Derecha": "Urbano"},
	{"Izquierda": "Crisis", "Derecha": "Oportunidad"},
	{"Izquierda": "Indigente", "Derecha": "Millonario"},
	{"Izquierda": "Cancion Triste", "Derecha": "Cancion Feliz"},
	{"Izquierda": "Lampiño", "Derecha": "Peludo"},
	{"Izquierda": "Fantasia", "Derecha": "Ciencia Ficcion"},
	{"Izquierda": "Trabajo", "Derecha": "Carrera"},
	{"Izquierda": "Duro", "Derecha": "Suave"},
	{"Izquierda": "Mal Hombre", "Derecha": "Buen Hombre"},
	{"Izquierda": "Rico Olor", "Derecha": "Feo Olor"},
	{"Izquierda": "Inutil", "Derecha": "Util"},
	{"Izquierda": "Dividido", "Derecha": "Entero"},
	{"Izquierda": "Poco Higienico", "Derecha": "Higienico"},
	{"Izquierda": "Redondeado", "Derecha": "Punteagudo"},
	{"Izquierda": "Poco en Onda", "Derecha": "En Onda"},
	{"Izquierda": "Asqueroso", "Derecha": "Sabroso"},
	{"Izquierda": "No se evapora", "Derecha": "Se evapora"},
	{"Izquierda": "Debil", "Derecha": "Fuerte"},
	{"Izquierda": "Relajante", "Derecha": "Estresante"},
	{"Izquierda": "Actividad Aburrida", "Derecha": "Actividad Divertida"},
	{"Izquierda": "Costoso", "Derecha": "Valioso"},
	{"Izquierda": "Socialista", "Derecha": "Capitalista"},
	{"Izquierda": "80s", "Derecha": "90s"},
	{"Izquierda": "Inutil en una emergencia", "Derecha": "Util en una emergencia"},
	{"Izquierda": "Villano", "Derecha": "Heroe"},
	{"Izquierda": "Lo mejor de Internet", "Derecha": "Lo peor de Internet"},
	{"Izquierda": "Antiguo", "Derecha": "Moderno"},
	{"Izquierda": "Racional", "Derecha": "Espiritual"},
	{"Izquierda": "Comedia", "Derecha": "Drama"},
	{"Izquierda": "Teoría conspirativa", "Derecha": "Hecho comprobado"},
	{"Izquierda": "Limitado", "Derecha": "Infinito"},
	{"Izquierda": "Extraño", "Derecha": "Inusual"},
	{"Izquierda": "Libro subestimado", "Derecha": "Libro sobrevalorado"},
	{"Izquierda": "Buena inversión ", "Derecha": "Mala inversión"},
	{"Izquierda": "Tembleque", "Derecha": "Inmóvil"},
	{"Izquierda": "Podria vencer a un tiburón", "Derecha": "No podria vencer a un tiburón"},
	{"Izquierda": "No ético comerlo", "Derecha": "Ético comerlo"},
	{"Izquierda": "Liberal", "Derecha": "Conservador"},
	{"Izquierda": "Baja calidad", "Derecha": "Buena calidad"},
	{"Izquierda": "Gryffindor", "Derecha": "Slytherin"},
	{"Izquierda": "Trabajo", "Derecha": "Carrera"},
	{"Izquierda": "Baja calidad", "Derecha": "Alta calidad"},
	{"Izquierda": "Sucede despacio", "Derecha": "Sucede de repente"},
	{"Izquierda": "Parte del cuerpo inutil", "Derecha": "Parte del cuerpo útil"},
	{"Izquierda": "Inflexible", "Derecha": "Flexible"},
	{"Izquierda": "Mental", "Derecha": "Físico"},
	{"Izquierda": "Derecho", "Derecha": "Curvo"},
	{"Izquierda": "Producción Masiva", "Derecha": "Artesanal"},
	{"Izquierda": "Problema de primer mundo", "Derecha": "Problema actual"},
	{"Izquierda": "Chisme", "Derecha": "Noticias"},
	{"Izquierda": "Mala Película", "Derecha": "Buena Pelicula"},
	{"Izquierda": "Introvertido", "Derecha": "Extrovertido"},
	{"Izquierda": "Basico", "Derecha": "Increible"}
]
