# -*- coding: utf-8 -*-
"""
Mazo de Crisis del JUEGO BASE (61 cartas oficiales, hoja 'crisis' game=B).
Cada carta: colores/dificultad del chequeo, icono de salto (jump), activación
de naves Cylon, decisor (activo/presidente/almirante) y el texto oficial.
- tipo 'chequeo': Pass/Fail; si tiene 'alternativa', el decisor elige entre
  intentar el chequeo o tomar la alternativa garantizada (opción 'OR').
- tipo 'eleccion': el decisor elige entre dos opciones directas.
- tipo 'evento': efecto inmediato.
Efectos no modelables se muestran en el texto.
"""

CRISIS_DECK = [
    {
        "titulo": "A traitor accused",
        "texto": "Current Player Chooses: Pass: No Effect; Fail: the Current Player chooses a character to send to the \"Brig.\" OR The Current Player discards 5 Skill Cards.",
        "tipo": "chequeo",
        "decisor": "activo",
        "colores": ["Politica", "Liderazgo"],
        "dificultad": 8,
        "exito": [{"tipo": "mensaje", "texto": "Sin efecto."}],
        "fracaso": [{"tipo": "mensaje", "texto": "Sin efecto adicional."}],
        "alternativa": {"label": "🛡️ The Current Player discards 5 Skill Cards", "efectos": [{"tipo": "mensaje", "texto": "(según texto)"}]},
        "jump": 1,
        "activar_cylons": True,
    },
    {
        "titulo": "Admiral Grilled",
        "texto": "Current Player Chooses: Pass: No Effect; Fail: -1 Morale, and the Admiral discards 2 Skill Cards. OR -1 Morale.",
        "tipo": "chequeo",
        "decisor": "activo",
        "colores": ["Politica", "Liderazgo"],
        "dificultad": 9,
        "exito": [{"tipo": "mensaje", "texto": "Sin efecto."}],
        "fracaso": [{"tipo": "recurso", "recurso": "moral", "delta": -1}],
        "alternativa": {"label": "🛡️ -1 Morale", "efectos": [{"tipo": "recurso", "recurso": "moral", "delta": -1}]},
        "jump": 1,
        "activar_cylons": True,
    },
    {
        "titulo": "Analyze Enemy Fighter",
        "texto": "Current Player Chooses: Pass: Repair 1 destroyed Raptor; Fail: -1 population. OR Roll a die. If 4 or lower, -1 population and the current player discards 2 Skill Cards.",
        "tipo": "chequeo",
        "decisor": "activo",
        "colores": ["Tactica", "Ingenieria"],
        "dificultad": 7,
        "exito": [{"tipo": "mensaje", "texto": "Sin efecto."}],
        "fracaso": [{"tipo": "recurso", "recurso": "poblacion", "delta": -1}],
        "alternativa": {"label": "🛡️ Roll a die. If 4 or lower, -1 population and the cur…", "efectos": [{"tipo": "recurso", "recurso": "poblacion", "delta": -1}]},
        "jump": 1,
        "activar_cylons": True,
    },
    {
        "titulo": "Bomb Threat",
        "texto": "Current Player Chooses: Pass: No Effect; Fail: -1 Morale and draw a Civilian ship and destroy it. OR Roll a die. If 4 or lower, trigger the \"Fail\" effect of this card.",
        "tipo": "chequeo",
        "decisor": "activo",
        "colores": ["Politica", "Liderazgo", "Tactica"],
        "dificultad": 13,
        "exito": [{"tipo": "mensaje", "texto": "Sin efecto."}],
        "fracaso": [{"tipo": "recurso", "recurso": "moral", "delta": -1}, {"tipo": "destruir_civil"}],
        "alternativa": {"label": "🛡️ Roll a die. If 4 or lower, trigger the \"Fail\" effect…", "efectos": [{"tipo": "mensaje", "texto": "(según texto)"}]},
        "jump": 1,
        "activar_cylons": True,
    },
    {
        "titulo": "Build Cylon Detector",
        "texto": "Admiral Chooses: Discard 1 Nuke Token. If you do not have any Nuke tokens, you may not choose this option. OR -1 Morale, and the Admiral discards 2 Skill Cards.",
        "tipo": "eleccion",
        "decisor": "almirante",
        "opciones": [{"label": "A) Discard 1 Nuke Token. If you do not have any Nuke to…", "efectos": [{"tipo": "mensaje", "texto": "(según texto)"}]}, {"label": "B) -1 Morale, and the Admiral discards 2 Skill Cards", "efectos": [{"tipo": "recurso", "recurso": "moral", "delta": -1}]}],
        "jump": 0,
        "activar_cylons": True,
    },
    {
        "titulo": "Colonial Day",
        "texto": "Current Player Chooses: Pass: +1 Morale; Fail: -2 Morale. OR -1 Morale.",
        "tipo": "chequeo",
        "decisor": "activo",
        "colores": ["Politica", "Tactica"],
        "dificultad": 10,
        "exito": [{"tipo": "recurso", "recurso": "moral", "delta": 1}],
        "fracaso": [{"tipo": "recurso", "recurso": "moral", "delta": -2}],
        "alternativa": {"label": "🛡️ -1 Morale", "efectos": [{"tipo": "recurso", "recurso": "moral", "delta": -1}]},
        "jump": 1,
        "activar_cylons": True,
    },
    {
        "titulo": "Crash Landing",
        "texto": "Pass: No Effect; Fail: The Admiral may spend 1 fuel. If he does not, -1 Morale, and the Current Player is sent to \"Sickbay.\"",
        "tipo": "chequeo",
        "decisor": "activo",
        "colores": ["Tactica", "Pilotaje"],
        "dificultad": 6,
        "exito": [{"tipo": "mensaje", "texto": "Sin efecto."}],
        "fracaso": [{"tipo": "recurso", "recurso": "combustible", "delta": -1}, {"tipo": "recurso", "recurso": "moral", "delta": -1}],
        "jump": 0,
        "activar_cylons": True,
    },
    {
        "titulo": "Crippled Raider",
        "texto": "Current Player Chooses: Pass: Increase the Jump Prep track by 1; Fail: -1 population. OR Roll a die. If 4 or lower, place 3 Raiders in front of Galactica and 1 Civilian ship behind it.",
        "tipo": "chequeo",
        "decisor": "activo",
        "colores": ["Tactica", "Ingenieria"],
        "dificultad": 10,
        "exito": [{"tipo": "jump_prep", "delta": 1}],
        "fracaso": [{"tipo": "recurso", "recurso": "poblacion", "delta": -1}],
        "alternativa": {"label": "🛡️ Roll a die. If 4 or lower, place 3 Raiders in front …", "efectos": [{"tipo": "raiders", "cantidad": 3}]},
        "jump": 1,
        "activar_cylons": True,
    },
    {
        "titulo": "Cylon Accusation",
        "texto": "Pass: No Effect; Fail: The Current Player is placed in the \"Brig\" location.",
        "tipo": "chequeo",
        "decisor": "activo",
        "colores": ["Politica", "Liderazgo", "Tactica"],
        "dificultad": 10,
        "exito": [{"tipo": "mensaje", "texto": "Sin efecto."}],
        "fracaso": [{"tipo": "mensaje", "texto": "Sin efecto adicional."}],
        "jump": 0,
        "activar_cylons": True,
    },
    {
        "titulo": "Cylon Screenings",
        "texto": "Current Player Chooses: Pass: No Effect; Fail: -1 Morale, and the Current Player looks at 1 random Loyalty Card belonging to the President or Admiral. OR Each player discards 2 Skill Cards.",
        "tipo": "chequeo",
        "decisor": "activo",
        "colores": ["Politica", "Liderazgo"],
        "dificultad": 9,
        "exito": [{"tipo": "mensaje", "texto": "Sin efecto."}],
        "fracaso": [{"tipo": "recurso", "recurso": "moral", "delta": -1}],
        "alternativa": {"label": "🛡️ Each player discards 2 Skill Cards", "efectos": [{"tipo": "mensaje", "texto": "(según texto)"}]},
        "jump": 0,
        "activar_cylons": True,
    },
    {
        "titulo": "Cylon Tracking Device",
        "texto": "Pass: No Effect; Fail: Destroy 1 Raptor and place a Basestar in front of Galactica and 2 Civilian ships behind it.",
        "tipo": "chequeo",
        "decisor": "activo",
        "colores": ["Tactica", "Pilotaje", "Ingenieria"],
        "dificultad": 10,
        "exito": [{"tipo": "mensaje", "texto": "Sin efecto."}],
        "fracaso": [{"tipo": "mensaje", "texto": "Sin efecto adicional."}],
        "jump": 0,
        "activar_cylons": True,
    },
    {
        "titulo": "Cylon Virus",
        "texto": "Pass: No Effect; Fail: All characters in the \"FTL Control\" location are sent to \"Sickbay.\" Then place 1 Centurion marker at the start of the Boarding Party track.",
        "tipo": "chequeo",
        "decisor": "activo",
        "colores": ["Tactica", "Ingenieria"],
        "dificultad": 13,
        "exito": [{"tipo": "mensaje", "texto": "Sin efecto."}],
        "fracaso": [{"tipo": "mensaje", "texto": "Sin efecto adicional."}],
        "jump": 0,
        "activar_cylons": True,
    },
    {
        "titulo": "Declare Martial Law",
        "texto": "Admiral Chooses: -1 Morale and the Admiral receives the President Title. OR -1 Population and the Admiral discards 2 Skill Cards",
        "tipo": "eleccion",
        "decisor": "almirante",
        "opciones": [{"label": "A) -1 Morale and the Admiral receives the President Title", "efectos": [{"tipo": "recurso", "recurso": "moral", "delta": -1}]}, {"label": "B) -1 Population and the Admiral discards 2 Skill Cards", "efectos": [{"tipo": "recurso", "recurso": "poblacion", "delta": -1}]}],
        "jump": 0,
        "activar_cylons": True,
    },
    {
        "titulo": "Detector Sabotage",
        "texto": "Pass: No Effect; Fail: All characters in the \"Research Lab\" location are sent to \"Sickbay.\" Keep this card in play. Players may not look at other players' Loyalty Cards.",
        "tipo": "chequeo",
        "decisor": "activo",
        "colores": ["Liderazgo", "Tactica"],
        "dificultad": 8,
        "exito": [{"tipo": "mensaje", "texto": "Sin efecto."}],
        "fracaso": [{"tipo": "mensaje", "texto": "Sin efecto adicional."}],
        "jump": 1,
        "activar_cylons": True,
    },
    {
        "titulo": "Elections Loom",
        "texto": "Pass: No Effect; 5+: -1 Morale; Fail: -1 Morale, and the President discards 4 Skill Cards.",
        "tipo": "chequeo",
        "decisor": "activo",
        "colores": ["Politica", "Liderazgo"],
        "dificultad": 8,
        "exito": [{"tipo": "mensaje", "texto": "Sin efecto."}],
        "fracaso": [{"tipo": "recurso", "recurso": "moral", "delta": -1}],
        "jump": 1,
        "activar_cylons": True,
    },
    {
        "titulo": "Food Shortage",
        "texto": "President Chooses: -2 Food. OR -1 Food. The President discards 2 Skill Cards and the Current Player discards 3 Skill Cards.",
        "tipo": "eleccion",
        "decisor": "presidente",
        "opciones": [{"label": "A) -2 Food", "efectos": [{"tipo": "recurso", "recurso": "comida", "delta": -2}]}, {"label": "B) -1 Food. The President discards 2 Skill Cards and th…", "efectos": [{"tipo": "recurso", "recurso": "comida", "delta": -1}]}],
        "jump": 1,
        "activar_cylons": True,
    },
    {
        "titulo": "Forced Water Mining",
        "texto": "Current Player Chooses: Pass: +1 Food; Fail: -1 Population, -1 Morale. OR +1 Food, -1 Morale, and each player discards 1 random Skill Card.",
        "tipo": "chequeo",
        "decisor": "activo",
        "colores": ["Politica", "Liderazgo", "Tactica", "Ingenieria"],
        "dificultad": 17,
        "exito": [{"tipo": "recurso", "recurso": "comida", "delta": 1}],
        "fracaso": [{"tipo": "recurso", "recurso": "poblacion", "delta": -1}, {"tipo": "recurso", "recurso": "moral", "delta": -1}],
        "alternativa": {"label": "🛡️ +1 Food, -1 Morale, and each player discards 1 rando…", "efectos": [{"tipo": "recurso", "recurso": "comida", "delta": 1}, {"tipo": "recurso", "recurso": "moral", "delta": -1}]},
        "jump": 1,
        "activar_cylons": True,
    },
    {
        "titulo": "Fulfiller of Prophecy",
        "texto": "Current Player Chooses: Pass: The Current Player draws 1 Politics Skill Card; Fail: -1 Population. OR Current Player discards 1 Skill Card. After the Activate Cylon Ships step, return to the Resolve Crisis step (Draw a new Crisis Card and resolve it).",
        "tipo": "chequeo",
        "decisor": "activo",
        "colores": ["Politica", "Liderazgo"],
        "dificultad": 6,
        "exito": [{"tipo": "mensaje", "texto": "Sin efecto."}],
        "fracaso": [{"tipo": "recurso", "recurso": "poblacion", "delta": -1}],
        "alternativa": {"label": "🛡️ Current Player discards 1 Skill Card. After the Acti…", "efectos": [{"tipo": "mensaje", "texto": "(según texto)"}]},
        "jump": 0,
        "activar_cylons": True,
    },
    {
        "titulo": "Guilt by Collusion",
        "texto": "Pass: The Current Player may choose a character to move to the \"Brig.\"; Fail: -1 Morale.",
        "tipo": "chequeo",
        "decisor": "activo",
        "colores": ["Liderazgo", "Tactica"],
        "dificultad": 9,
        "exito": [{"tipo": "mensaje", "texto": "Sin efecto."}],
        "fracaso": [{"tipo": "recurso", "recurso": "moral", "delta": -1}],
        "jump": 1,
        "activar_cylons": True,
    },
    {
        "titulo": "Hangar Accident",
        "texto": "Pass: No Effect; 7+: -1 Population; Fail: -1 Population and damage 2 Vipers in the \"Reserves.\"",
        "tipo": "chequeo",
        "decisor": "activo",
        "colores": ["Tactica", "Pilotaje", "Ingenieria"],
        "dificultad": 10,
        "exito": [{"tipo": "mensaje", "texto": "Sin efecto."}],
        "fracaso": [{"tipo": "recurso", "recurso": "poblacion", "delta": -1}],
        "jump": 1,
        "activar_cylons": True,
    },
    {
        "titulo": "Informing the Public",
        "texto": "Current Player Chooses: Pass: Current Player looks at 1 random Loyalty Card belonging to any player; Fail: -2 Morale. OR Roll a die. On a 4 or lower, -1 Morale and -1 Population.",
        "tipo": "chequeo",
        "decisor": "activo",
        "colores": ["Politica", "Liderazgo"],
        "dificultad": 7,
        "exito": [{"tipo": "mensaje", "texto": "Sin efecto."}],
        "fracaso": [{"tipo": "recurso", "recurso": "moral", "delta": -2}],
        "alternativa": {"label": "🛡️ Roll a die. On a 4 or lower, -1 Morale and -1 Popula…", "efectos": [{"tipo": "recurso", "recurso": "moral", "delta": -1}, {"tipo": "recurso", "recurso": "poblacion", "delta": -1}]},
        "jump": 1,
        "activar_cylons": True,
    },
    {
        "titulo": "Jump Computer Failure",
        "texto": "Pass: No Effect; Fail: -1 Population and move the Fleet token 1 space towards the start of the Jump Prep track.",
        "tipo": "chequeo",
        "decisor": "activo",
        "colores": ["Tactica", "Ingenieria"],
        "dificultad": 7,
        "exito": [{"tipo": "mensaje", "texto": "Sin efecto."}],
        "fracaso": [{"tipo": "recurso", "recurso": "poblacion", "delta": -1}],
        "jump": 0,
        "activar_cylons": True,
    },
    {
        "titulo": "Keep Tabs on Visitor",
        "texto": "Current Player Chooses: Pass: No Effect; Fail: Roll a die. If 4 or lower, -2 Population. OR The Current Player discards 4 random Skill Cards.",
        "tipo": "chequeo",
        "decisor": "activo",
        "colores": ["Politica", "Liderazgo", "Tactica"],
        "dificultad": 12,
        "exito": [{"tipo": "mensaje", "texto": "Sin efecto."}],
        "fracaso": [{"tipo": "recurso", "recurso": "poblacion", "delta": -2}],
        "alternativa": {"label": "🛡️ The Current Player discards 4 random Skill Cards", "efectos": [{"tipo": "mensaje", "texto": "(según texto)"}]},
        "jump": 1,
        "activar_cylons": True,
    },
    {
        "titulo": "Legendary Discovery",
        "texto": "Pass: Place this card next to the Kobol Objective card. It counts as 1 Distance; Fail: -1 Food and destroy 1 Raptor.",
        "tipo": "chequeo",
        "decisor": "activo",
        "colores": ["Tactica", "Pilotaje"],
        "dificultad": 14,
        "exito": [{"tipo": "mensaje", "texto": "Sin efecto."}],
        "fracaso": [{"tipo": "recurso", "recurso": "comida", "delta": -1}],
        "jump": 0,
        "activar_cylons": True,
    },
    {
        "titulo": "Loss of a Friend",
        "texto": "Pass: No Effect; 7+: The Current Player discards 2 Skill Cards; Fail: -1 Morale, and the Current Player discards 2 Skill Cards.",
        "tipo": "chequeo",
        "decisor": "activo",
        "colores": ["Politica", "Liderazgo"],
        "dificultad": 9,
        "exito": [{"tipo": "mensaje", "texto": "Sin efecto."}],
        "fracaso": [{"tipo": "recurso", "recurso": "moral", "delta": -1}],
        "jump": 1,
        "activar_cylons": True,
    },
    {
        "titulo": "Low Supplies",
        "texto": "Pass: No Effect; Fail: -1 Morale. If Food is less than 6, -1 additional Morale.",
        "tipo": "chequeo",
        "decisor": "activo",
        "colores": ["Politica", "Liderazgo"],
        "dificultad": 7,
        "exito": [{"tipo": "mensaje", "texto": "Sin efecto."}],
        "fracaso": [{"tipo": "recurso", "recurso": "moral", "delta": -1}],
        "jump": 0,
        "activar_cylons": True,
    },
    {
        "titulo": "Mandatory Testing",
        "texto": "Pass: The President looks at 1 random Loyalty card of the Current Player; 9+: No Effect; Fail: -1 Morale.",
        "tipo": "chequeo",
        "decisor": "activo",
        "colores": ["Politica", "Liderazgo"],
        "dificultad": 13,
        "exito": [{"tipo": "mensaje", "texto": "Sin efecto."}],
        "fracaso": [{"tipo": "recurso", "recurso": "moral", "delta": -1}],
        "jump": 1,
        "activar_cylons": True,
    },
    {
        "titulo": "Missing G4 Explosives",
        "texto": "Pass: No Effect; Fail: -1 Food, and all characters in the \"Armory\" location are sent to the \"Brig.\"",
        "tipo": "chequeo",
        "decisor": "activo",
        "colores": ["Liderazgo", "Tactica"],
        "dificultad": 7,
        "exito": [{"tipo": "mensaje", "texto": "Sin efecto."}],
        "fracaso": [{"tipo": "recurso", "recurso": "comida", "delta": -1}],
        "jump": 0,
        "activar_cylons": True,
    },
    {
        "titulo": "Network Computers",
        "texto": "Current Player Chooses: Pass: Increase the Jump Prep track by 1; Fail: -1 Population and place 1 Centurion marker at the start of the Boarding Party track. OR -1 Population and decrease the Jump Prep track by 1.",
        "tipo": "chequeo",
        "decisor": "activo",
        "colores": ["Politica", "Tactica", "Ingenieria"],
        "dificultad": 11,
        "exito": [{"tipo": "jump_prep", "delta": 1}],
        "fracaso": [{"tipo": "recurso", "recurso": "poblacion", "delta": -1}],
        "alternativa": {"label": "🛡️ -1 Population and decrease the Jump Prep track by 1", "efectos": [{"tipo": "recurso", "recurso": "poblacion", "delta": -1}, {"tipo": "jump_prep", "delta": -1}]},
        "jump": 1,
        "activar_cylons": True,
    },
    {
        "titulo": "Prison Labor",
        "texto": "Pass: No Effect; Fail: -1 Morale, -1 Food.",
        "tipo": "chequeo",
        "decisor": "activo",
        "colores": ["Politica", "Liderazgo", "Tactica"],
        "dificultad": 10,
        "exito": [{"tipo": "mensaje", "texto": "Sin efecto."}],
        "fracaso": [{"tipo": "recurso", "recurso": "moral", "delta": -1}, {"tipo": "recurso", "recurso": "comida", "delta": -1}],
        "jump": 0,
        "activar_cylons": True,
    },
    {
        "titulo": "Prisoner Revolt",
        "texto": "Pass: No Effect; 6+: -1 Population; Fail: -1 Population, and the President chooses another player to receive the President title.",
        "tipo": "chequeo",
        "decisor": "activo",
        "colores": ["Politica", "Liderazgo", "Tactica"],
        "dificultad": 11,
        "exito": [{"tipo": "mensaje", "texto": "Sin efecto."}],
        "fracaso": [{"tipo": "recurso", "recurso": "poblacion", "delta": -1}],
        "jump": 1,
        "activar_cylons": True,
    },
    {
        "titulo": "Requested Resignation",
        "texto": "Admiral Chooses: The President and Admiral both discard 2 Skill Cards. OR The President may choose to give the President title to the Admiral, or move to the \"Brig\" location.",
        "tipo": "eleccion",
        "decisor": "almirante",
        "opciones": [{"label": "A) The President and Admiral both discard 2 Skill Cards", "efectos": [{"tipo": "mensaje", "texto": "(según texto)"}]}, {"label": "B) The President may choose to give the President title…", "efectos": [{"tipo": "mensaje", "texto": "(según texto)"}]}],
        "jump": 0,
        "activar_cylons": True,
    },
    {
        "titulo": "Rescue Caprica Survivors",
        "texto": "President Chooses:-1 Fuel, -1 Food, +1 Population. OR -1 Morale.",
        "tipo": "eleccion",
        "decisor": "presidente",
        "opciones": [{"label": "A) -1 Fuel, -1 Food, +1 Population", "efectos": [{"tipo": "recurso", "recurso": "combustible", "delta": -1}, {"tipo": "recurso", "recurso": "comida", "delta": -1}, {"tipo": "recurso", "recurso": "poblacion", "delta": 1}]}, {"label": "B) -1 Morale", "efectos": [{"tipo": "recurso", "recurso": "moral", "delta": -1}]}],
        "jump": 1,
        "activar_cylons": True,
    },
    {
        "titulo": "Rescue Mission (B/*)",
        "texto": "Admiral Chooses: -1 Morale, Current Player is sent to \"Sickbay.\" OR -1 Fuel and destroy 1 Raptor.",
        "tipo": "eleccion",
        "decisor": "almirante",
        "opciones": [{"label": "A) -1 Morale, Current Player is sent to \"Sickbay.\"", "efectos": [{"tipo": "recurso", "recurso": "moral", "delta": -1}]}, {"label": "B) -1 Fuel and destroy 1 Raptor", "efectos": [{"tipo": "recurso", "recurso": "combustible", "delta": -1}]}],
        "jump": 1,
        "activar_cylons": True,
    },
    {
        "titulo": "Rescue Mission (R/*)",
        "texto": "Admiral Chooses: -1 Morale, Current Player is sent to \"Sickbay.\" OR -1 Fuel and destroy 1 Raptor.",
        "tipo": "eleccion",
        "decisor": "almirante",
        "opciones": [{"label": "A) -1 Morale, Current Player is sent to \"Sickbay.\"", "efectos": [{"tipo": "recurso", "recurso": "moral", "delta": -1}]}, {"label": "B) -1 Fuel and destroy 1 Raptor", "efectos": [{"tipo": "recurso", "recurso": "combustible", "delta": -1}]}],
        "jump": 1,
        "activar_cylons": True,
    },
    {
        "titulo": "Rescue the Fleet",
        "texto": "Admiral Chooses: -2 Population. OR -1 Morale, place 1 Basestar and 3 Raiders in front of Galactica, and 3 Civilian ships behind Galactica.",
        "tipo": "eleccion",
        "decisor": "almirante",
        "opciones": [{"label": "A) -2 Population", "efectos": [{"tipo": "recurso", "recurso": "poblacion", "delta": -2}]}, {"label": "B) -1 Morale, place 1 Basestar and 3 Raiders in front o…", "efectos": [{"tipo": "recurso", "recurso": "moral", "delta": -1}]}],
        "jump": 1,
        "activar_cylons": True,
    },
    {
        "titulo": "Resistance",
        "texto": "Pass: No Effect; 9+: -1 Food; Fail: -1 Food, -1 Fuel.",
        "tipo": "chequeo",
        "decisor": "activo",
        "colores": ["Politica", "Liderazgo", "Tactica"],
        "dificultad": 12,
        "exito": [{"tipo": "mensaje", "texto": "Sin efecto."}],
        "fracaso": [{"tipo": "recurso", "recurso": "comida", "delta": -1}, {"tipo": "recurso", "recurso": "combustible", "delta": -1}],
        "jump": 1,
        "activar_cylons": True,
    },
    {
        "titulo": "Riots (B/*)",
        "texto": "Admiral Chooses: -1 Food, -1 Morale. OR -1 Population, -1 Fuel.",
        "tipo": "eleccion",
        "decisor": "almirante",
        "opciones": [{"label": "A) -1 Food, -1 Morale", "efectos": [{"tipo": "recurso", "recurso": "comida", "delta": -1}, {"tipo": "recurso", "recurso": "moral", "delta": -1}]}, {"label": "B) -1 Population, -1 Fuel", "efectos": [{"tipo": "recurso", "recurso": "poblacion", "delta": -1}, {"tipo": "recurso", "recurso": "combustible", "delta": -1}]}],
        "jump": 1,
        "activar_cylons": True,
    },
    {
        "titulo": "Riots (L/-)",
        "texto": "Admiral Chooses: -1 Food, -1 Morale. OR -1 Population, -1 Fuel.",
        "tipo": "eleccion",
        "decisor": "almirante",
        "opciones": [{"label": "A) -1 Food, -1 Morale", "efectos": [{"tipo": "recurso", "recurso": "comida", "delta": -1}, {"tipo": "recurso", "recurso": "moral", "delta": -1}]}, {"label": "B) -1 Population, -1 Fuel", "efectos": [{"tipo": "recurso", "recurso": "poblacion", "delta": -1}, {"tipo": "recurso", "recurso": "combustible", "delta": -1}]}],
        "jump": 0,
        "activar_cylons": True,
    },
    {
        "titulo": "Scouting for Fuel",
        "texto": "Current Player Chooses: Pass: +1 Fuel; Fail: -1 Fuel and destroy 1 Raptor. OR Roll a die. If 4 or lower, -1 Fuel.",
        "tipo": "chequeo",
        "decisor": "activo",
        "colores": ["Tactica", "Pilotaje"],
        "dificultad": 12,
        "exito": [{"tipo": "recurso", "recurso": "combustible", "delta": 1}],
        "fracaso": [{"tipo": "recurso", "recurso": "combustible", "delta": -1}],
        "alternativa": {"label": "🛡️ Roll a die. If 4 or lower, -1 Fuel", "efectos": [{"tipo": "recurso", "recurso": "combustible", "delta": -1}]},
        "jump": 1,
        "activar_cylons": True,
    },
    {
        "titulo": "Scouting for Water",
        "texto": "Current Player Chooses: Pass: +1 Food; Fail: -1 Fuel and destroy 1 Raptor. OR -1 Food.",
        "tipo": "chequeo",
        "decisor": "activo",
        "colores": ["Tactica", "Pilotaje"],
        "dificultad": 9,
        "exito": [{"tipo": "recurso", "recurso": "comida", "delta": 1}],
        "fracaso": [{"tipo": "recurso", "recurso": "combustible", "delta": -1}],
        "alternativa": {"label": "🛡️ -1 Food", "efectos": [{"tipo": "recurso", "recurso": "comida", "delta": -1}]},
        "jump": 1,
        "activar_cylons": True,
    },
    {
        "titulo": "Security Breach",
        "texto": "Pass: No Effect; Fail: -1 Morale, and all characters in the \"Command\" location are sent to \"Sickbay.\"",
        "tipo": "chequeo",
        "decisor": "activo",
        "colores": ["Liderazgo", "Tactica"],
        "dificultad": 6,
        "exito": [{"tipo": "mensaje", "texto": "Sin efecto."}],
        "fracaso": [{"tipo": "recurso", "recurso": "moral", "delta": -1}],
        "jump": 0,
        "activar_cylons": True,
    },
    {
        "titulo": "Send Survey Team",
        "texto": "Current Player Chooses: Pass: No Effect; Fail: The Current Player is sent to \"Sickbay\" and destroy 1 Raptor. OR Roll a die. If 5 or less, -1 Fuel.",
        "tipo": "chequeo",
        "decisor": "activo",
        "colores": ["Tactica", "Pilotaje", "Ingenieria"],
        "dificultad": 15,
        "exito": [{"tipo": "mensaje", "texto": "Sin efecto."}],
        "fracaso": [{"tipo": "mensaje", "texto": "Sin efecto adicional."}],
        "alternativa": {"label": "🛡️ Roll a die. If 5 or less, -1 Fuel", "efectos": [{"tipo": "recurso", "recurso": "combustible", "delta": -1}]},
        "jump": 1,
        "activar_cylons": True,
    },
    {
        "titulo": "Sleep Deprivation",
        "texto": "Admiral Chooses: Return all undamaged Vipers on the game board to the \"Reserves.\" Current Player is sent to \"Sickbay.\" OR -1 Morale.",
        "tipo": "eleccion",
        "decisor": "almirante",
        "opciones": [{"label": "A) Return all undamaged Vipers on the game board to the…", "efectos": [{"tipo": "mensaje", "texto": "(según texto)"}]}, {"label": "B) -1 Morale", "efectos": [{"tipo": "recurso", "recurso": "moral", "delta": -1}]}],
        "jump": 1,
        "activar_cylons": True,
    },
    {
        "titulo": "Terrorist Bomber",
        "texto": "Pass: No Effect; Fail: -1 Morale, and the Current Player is sent to \"Sickbay.\"",
        "tipo": "chequeo",
        "decisor": "activo",
        "colores": ["Liderazgo", "Tactica"],
        "dificultad": 9,
        "exito": [{"tipo": "mensaje", "texto": "Sin efecto."}],
        "fracaso": [{"tipo": "recurso", "recurso": "moral", "delta": -1}],
        "jump": 1,
        "activar_cylons": True,
    },
    {
        "titulo": "Terrorist Investigations",
        "texto": "Pass: Current Player looks at 1 random Loyalty Card belonging to any player; 6+: No effect; Fail: -1 Morale.",
        "tipo": "chequeo",
        "decisor": "activo",
        "colores": ["Politica", "Liderazgo"],
        "dificultad": 12,
        "exito": [{"tipo": "mensaje", "texto": "Sin efecto."}],
        "fracaso": [{"tipo": "recurso", "recurso": "moral", "delta": -1}],
        "jump": 1,
        "activar_cylons": True,
    },
    {
        "titulo": "The Olympic Carrier",
        "texto": "Pass: No Effect; 8+: -1 Population; Fail: -1 Morale, -1 Population.",
        "tipo": "chequeo",
        "decisor": "activo",
        "colores": ["Politica", "Liderazgo", "Pilotaje"],
        "dificultad": 11,
        "exito": [{"tipo": "mensaje", "texto": "Sin efecto."}],
        "fracaso": [{"tipo": "recurso", "recurso": "moral", "delta": -1}, {"tipo": "recurso", "recurso": "poblacion", "delta": -1}],
        "jump": 1,
        "activar_cylons": True,
    },
    {
        "titulo": "Unexpected Reunion",
        "texto": "Pass: No Effect; Fail: -1 Morale, and the Current Player discards his hand of Skill Cards.",
        "tipo": "chequeo",
        "decisor": "activo",
        "colores": ["Politica", "Liderazgo", "Tactica"],
        "dificultad": 8,
        "exito": [{"tipo": "mensaje", "texto": "Sin efecto."}],
        "fracaso": [{"tipo": "recurso", "recurso": "moral", "delta": -1}],
        "jump": 0,
        "activar_cylons": True,
    },
    {
        "titulo": "Unidentified Ship",
        "texto": "Pass: No Effect; Fail: -1 Population.",
        "tipo": "chequeo",
        "decisor": "activo",
        "colores": ["Tactica", "Pilotaje"],
        "dificultad": 10,
        "exito": [{"tipo": "mensaje", "texto": "Sin efecto."}],
        "fracaso": [{"tipo": "recurso", "recurso": "poblacion", "delta": -1}],
        "jump": 0,
        "activar_cylons": True,
    },
    {
        "titulo": "Water Sabotaged",
        "texto": "Current Player Chooses: Pass: No Effect; Fail: -2 Food. OR - 1 Food.",
        "tipo": "chequeo",
        "decisor": "activo",
        "colores": ["Politica", "Liderazgo", "Tactica"],
        "dificultad": 13,
        "exito": [{"tipo": "mensaje", "texto": "Sin efecto."}],
        "fracaso": [{"tipo": "recurso", "recurso": "comida", "delta": -2}],
        "alternativa": {"label": "🛡️ - 1 Food", "efectos": [{"tipo": "recurso", "recurso": "comida", "delta": -1}]},
        "jump": 1,
        "activar_cylons": True,
    },
    {
        "titulo": "Water Shortage (B/*)",
        "texto": "President Chooses: -1 Food. OR The President discards 2 Skill Cards, then the Current Player discards 3 Skill Cards.",
        "tipo": "eleccion",
        "decisor": "presidente",
        "opciones": [{"label": "A) -1 Food", "efectos": [{"tipo": "recurso", "recurso": "comida", "delta": -1}]}, {"label": "B) The President discards 2 Skill Cards, then the Curre…", "efectos": [{"tipo": "mensaje", "texto": "(según texto)"}]}],
        "jump": 1,
        "activar_cylons": True,
    },
    {
        "titulo": "Water Shortage (R/*)",
        "texto": "President Chooses: -1 Food. OR The President discards 2 Skill Cards, then the Current Player discards 3 Skill Cards.",
        "tipo": "eleccion",
        "decisor": "presidente",
        "opciones": [{"label": "A) -1 Food", "efectos": [{"tipo": "recurso", "recurso": "comida", "delta": -1}]}, {"label": "B) The President discards 2 Skill Cards, then the Curre…", "efectos": [{"tipo": "mensaje", "texto": "(según texto)"}]}],
        "jump": 0,
        "activar_cylons": True,
    },
    {
        "titulo": "Water Shortage (B/-)",
        "texto": "President Chooses: -1 Food. OR The President discards 2 Skill Cards, then the Current Player discards 3 Skill Cards.",
        "tipo": "eleccion",
        "decisor": "presidente",
        "opciones": [{"label": "A) -1 Food", "efectos": [{"tipo": "recurso", "recurso": "comida", "delta": -1}]}, {"label": "B) The President discards 2 Skill Cards, then the Curre…", "efectos": [{"tipo": "mensaje", "texto": "(según texto)"}]}],
        "jump": 0,
        "activar_cylons": True,
    },
    {
        "titulo": "Weapon Malfunction",
        "texto": "Pass: No Effect; Fail: Damage 2 Vipers in space areas. All characters in the \"Weapons Control\" location are sent to \"Sickbay.\"",
        "tipo": "chequeo",
        "decisor": "activo",
        "colores": ["Tactica", "Pilotaje", "Ingenieria"],
        "dificultad": 11,
        "exito": [{"tipo": "mensaje", "texto": "Sin efecto."}],
        "fracaso": [{"tipo": "mensaje", "texto": "Sin efecto adicional."}],
        "jump": 0,
        "activar_cylons": True,
    },
    {
        "titulo": "Witch Hunt",
        "texto": "Pass: No Effect; 6+: -1 Morale; Fail: -1 Morale. Current Player chooses a character and moves him to \"Sickbay.\"",
        "tipo": "chequeo",
        "decisor": "activo",
        "colores": ["Politica", "Liderazgo"],
        "dificultad": 10,
        "exito": [{"tipo": "mensaje", "texto": "Sin efecto."}],
        "fracaso": [{"tipo": "recurso", "recurso": "moral", "delta": -1}],
        "jump": 1,
        "activar_cylons": True,
    },
    {
        "titulo": "Bomb on Colonial One",
        "texto": "Pass: No Effect; Fail : -2 Morale, and all characters on Colonial One are sent to 'Sickbay'. Keep this card in play. Characters may not move to Colonial One for the rest of the game.",
        "tipo": "chequeo",
        "decisor": "activo",
        "colores": ["Tactica", "Pilotaje", "Ingenieria"],
        "dificultad": 15,
        "exito": [{"tipo": "mensaje", "texto": "Sin efecto."}],
        "fracaso": [{"tipo": "mensaje", "texto": "Sin efecto adicional."}],
        "jump": 0,
        "activar_cylons": False,
    },
    {
        "titulo": "Cylon Intruders",
        "texto": "Pass: No Effect; 14+: Place 1 Centurion marker at the start of the Boarding Party track; Fail: Damage Galactica and place 2 Centurion markers at the start of the Boarding Party Track.",
        "tipo": "chequeo",
        "decisor": "activo",
        "colores": ["Liderazgo", "Tactica"],
        "dificultad": 18,
        "exito": [{"tipo": "mensaje", "texto": "Sin efecto."}],
        "fracaso": [{"tipo": "mensaje", "texto": "Sin efecto adicional."}],
        "jump": 0,
        "activar_cylons": False,
    },
    {
        "titulo": "Fleet Mobilization",
        "texto": "Pass: Activate Basestars, Launch Raiders; Fail : -1 Morale, and Activate Basestars, Activate Raiders, Activate Heavy Raiders, Launch Raiders.",
        "tipo": "chequeo",
        "decisor": "activo",
        "colores": ["Liderazgo", "Tactica", "Pilotaje", "Ingenieria"],
        "dificultad": 24,
        "exito": [{"tipo": "mensaje", "texto": "Sin efecto."}],
        "fracaso": [{"tipo": "mensaje", "texto": "Sin efecto adicional."}],
        "jump": 0,
        "activar_cylons": False,
    },
    {
        "titulo": "Inbound Nukes",
        "texto": "Pass: No Effect; Fail: -1 Fuel, -1 Food, and -1 Population.",
        "tipo": "chequeo",
        "decisor": "activo",
        "colores": ["Liderazgo", "Tactica"],
        "dificultad": 15,
        "exito": [{"tipo": "mensaje", "texto": "Sin efecto."}],
        "fracaso": [{"tipo": "recurso", "recurso": "combustible", "delta": -1}, {"tipo": "recurso", "recurso": "comida", "delta": -1}, {"tipo": "recurso", "recurso": "poblacion", "delta": -1}],
        "jump": 0,
        "activar_cylons": False,
    },
    {
        "titulo": "Admirals Quarters",
        "texto": "Action: Choose a character, then pass this skill check to send him to the \"Brig\"",
        "tipo": "chequeo",
        "decisor": "activo",
        "colores": ["Liderazgo", "Tactica"],
        "dificultad": 7,
        "exito": [{"tipo": "mensaje", "texto": "Sin efecto."}],
        "fracaso": [{"tipo": "mensaje", "texto": "Sin efecto adicional."}],
        "jump": 0,
        "activar_cylons": False,
    },
    {
        "titulo": "Brig",
        "texto": "Action: Pass this skill check to move to any location",
        "tipo": "chequeo",
        "decisor": "activo",
        "colores": ["Politica", "Tactica"],
        "dificultad": 7,
        "exito": [{"tipo": "mensaje", "texto": "Sin efecto."}],
        "fracaso": [{"tipo": "mensaje", "texto": "Sin efecto adicional."}],
        "jump": 0,
        "activar_cylons": False,
    },
]


# Mazo de SÚPER CRISIS: efectos potentes que dispara un Cylon al revelarse.
# (Set inicial; el juego base tiene varias más.)  # VERIFICAR / COMPLETAR
SUPER_CRISIS_DECK = [
    {
        "id": "asalto_masivo",
        "titulo": "Asalto Masivo",
        "texto": "Una oleada de Raiders cae sobre la flota.",
        "efectos": [{"tipo": "raiders", "cantidad": 3},
                    {"tipo": "mensaje", "texto": "¡La flota es asediada!"}],
    },
    {
        "id": "sabotaje_combustible",
        "titulo": "Sabotaje de Combustible",
        "texto": "Los tanques de tylium son saboteados.",
        "efectos": [{"tipo": "recurso", "recurso": "combustible", "delta": -2}],
    },
    {
        "id": "terror_flota",
        "titulo": "Terror en la Flota",
        "texto": "El pánico cunde entre los civiles.",
        "efectos": [{"tipo": "recurso", "recurso": "moral", "delta": -2}],
    },
    {
        "id": "abordaje_total",
        "titulo": "Abordaje Total",
        "texto": "Centuriones inundan los pasillos de Galactica.",
        "efectos": [{"tipo": "centuriones", "delta": 2}],
    },
    {
        "id": "oleada_heavy_raiders",
        "titulo": "Oleada de Heavy Raiders",
        "texto": "Heavy Raiders se lanzan hacia el hangar de Galactica.",
        "efectos": [{"tipo": "heavy_raiders", "cantidad": 2}],
    },
    {
        "id": "refuerzos_cylon",
        "titulo": "Refuerzos Cylon",
        "texto": "Una Basestar llega con refuerzos.",
        "efectos": [{"tipo": "basestar", "cantidad": 1},
                    {"tipo": "raiders", "cantidad": 2}],
    },
]
